language: go
matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/protobuf"
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
    - glide
    - build-essential
    - jq
install:
  - bash scripts/install-protobuf.sh
  - make install-deps
  - make glide-install
  - make logrus-fix
  - make generate
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)

env:
  global:
  - PROTOBUF_VER="3.3.0"
